name: Rename and Update

on:
    #push:
    workflow_dispatch:
    schedule:
    - cron: '0 0 * * *'

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 1

            - name: Use Node.js (dependency)
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Update Site Data
              run: node ./.github/workflows/updateSiteData.js;

            - name: Verify New Site Data
              run: node ./.github/workflows/verifySiteData.js;

            - name: Check for modified files
              id: git-check
              run: echo modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi) >> $GITHUB_OUTPUT

            - name: Push
              if: steps.git-check.outputs.modified == 'true'
              run: |
                  git config --global user.email "71089234+Ahmad-A0@users.noreply.github.com"
                  git config --global user.name "Bot-A0"
                  git add .
                  git commit -am "ğŸŒ Update Site Data (ğŸ› ï¸ from Github Actions)" || true
                  git push || git pull --rebase && git push


